Model changes for sprint 23.15.
pax2pay/model-banking pull request #114
Opened 2023-08-28 15:13 UTC by marcushanses

2023-08-29 08:03 UTC, AntonCroner approved these changes

2023-08-29 08:03 UTC, AntonCroner commented on Amount.ts
> +	export const type = isly.tuple(isly.fromIs("isoly.Currency", isoly.Currency.is), isly.number())
-> isly.tuple(isly.string(isoly.Currency.types), isly.number())

2023-08-29 08:03 UTC, AntonCroner commented on Amounts.ts
> +	export const type = isly.record(isly.fromIs("isoly.Currency", isoly.Currency.is), isly.number())
-> isly.record(isly.string(isoly.Currency.types), isly.number())

2023-08-29 08:06 UTC, AntonCroner approved these changes

2023-08-30 06:57 UTC, SiFalorSum commented on Settlement/Entry/Unknown.ts
> +	export const type = Creatable.type.extend<Unknown>({ status: isly.string(["succeeded", "failed"]) })
Tests fail here with "ReferenceError: Cannot access 'Creatable' before initialization" - seems like namespaces aren't hoisted?

2023-08-31 12:00 UTC, SiFalorSum commented on Authorization/Status.ts
> +			if (error.error?.includes("Card with id"))
Is there a better way to deduce the error than from the error message, as it may be changed?

2023-09-04 11:45 UTC, AntonCroner requested changes

2023-09-04 11:45 UTC, AntonCroner commented on Settlement/index.ts
> +	calculated?: Settlement.Total
calculated -> outcome

2023-09-04 11:48 UTC, AntonCroner approved these changes

2023-09-05 07:35 UTC, AntonCroner approved these changes

2023-09-05 07:39 UTC, merged