Detailed transaction amount
pax2pay/model-banking pull request #433
Opened 2024-10-11 14:25 UTC by SiFalorSum

Closes https://github.com/pax2pay/worker-banking-ledger/issues/1566

2024-10-14 15:29 UTC, marcushanses requested changes

2024-10-14 15:29 UTC, marcushanses commented on Rule/State/Transaction.ts
> +		transaction: (ModelTransaction.Creatable & { counterpart: Address }) | ModelTransaction | ModelTransaction.Legacy,
Behöver inte stödja legacy här.

2024-10-14 15:29 UTC, marcushanses commented on Transaction/index.ts
> +	}
Gör till en typ. Transaction.Amount

2024-10-14 15:29 UTC, marcushanses commented on Transaction/index.ts
> +			charge: -1 * (state.transaction.original.charge?.total ?? 0),
I don't think we should swap signs since:
- processing: original + reserved = total
- finalized: original + charge = total

2024-10-14 16:12 UTC, AntonCroner requested changes

2024-10-14 16:12 UTC, AntonCroner commented on Transaction/index.ts
> +	export function amountFromState(state: Rule.State.Evaluated): Amount {
move functions to amount namespace

2024-10-14 16:12 UTC, AntonCroner commented on Transaction/index.ts
> +		export const is = type.is
save some lines by not exporting all the functions individually

2024-10-14 16:12 UTC, AntonCroner commented on Transaction/index.ts
> +		export namespace Event {
The event isn't legacy i don't think

2024-10-15 09:04 UTC, AntonCroner commented on Transaction/index.ts
> +			amount[type] += change
you need to use the isoly functions

2024-10-16 09:57 UTC, AntonCroner submitted a review, later dismissed

2024-10-16 11:17 UTC, marcushanses requested changes

2024-10-16 11:17 UTC, marcushanses commented on index.spec.ts
> +			amount: { original: -1, reserved: 0, charge: 0, total: -1 }, //
```suggestion
			amount: { original: -1, reserved: 0, charge: 0, total: -1 },
```

2024-10-16 11:17 UTC, marcushanses commented on index.spec.ts
> +			amount: { original: -1, reserved: 0, charge: 0, total: -1 }, //
```suggestion
			amount: { original: -1, reserved: 0, charge: 0, total: -1 },
```

2024-10-16 11:17 UTC, marcushanses commented on verifier/index.spec.ts
> +	amount: { original: -1, reserved: 0, charge: 0, total: -1 }, //
```suggestion
	amount: { original: -1, reserved: 0, charge: 0, total: -1 },
```

2024-10-16 11:25 UTC, marcushanses approved these changes

2024-10-16 11:25 UTC, merged